# Generated by Django 4.1.1 on 2024-02-21 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
